SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE IF NOT EXISTS game_scores (
  nb_victimes int(4) NOT NULL DEFAULT '0',
  nb_pieces int(4) NOT NULL DEFAULT '0',
  nb_morts int(4) NOT NULL DEFAULT '0',
  lastupdate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_id int(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS game_users (
  user_id int(4) NOT NULL,
  pseudo varchar(75) NOT NULL,
  `password` varchar(255) NOT NULL,
  email varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE game_scores
  ADD KEY user_id (user_id);

ALTER TABLE game_users
  ADD PRIMARY KEY (user_id),
  ADD UNIQUE KEY email (email);


ALTER TABLE game_users
  MODIFY user_id int(4) NOT NULL AUTO_INCREMENT;

ALTER TABLE game_scores
  ADD CONSTRAINT game_scores_ibfk_1 FOREIGN KEY (user_id) REFERENCES game_users (user_id) ON DELETE CASCADE;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
